feat: review app copy
filecoin-station/filecoin-station pull request #226
Opened 2022-10-13 10:17 UTC by jopedroliveira

Closes #225
This PR adds the first reviewed version of copy and some tweaks on CSS to better fit the copy in the containers.

2022-10-13 10:40 UTC, juliangruber commented
![Screenshot 2022-10-13 at 12 40 40](https://user-images.githubusercontent.com/10247/195575932-700bd8ef-7a9c-45f4-89a4-91522b9434ff.png)

This screen looks out of balance to me now 🤔

2022-10-13 10:42 UTC, jopedroliveira commented
> ![Screenshot 2022-10-13 at 12 40 40](https://user-images.githubusercontent.com/10247/195575932-700bd8ef-7a9c-45f4-89a4-91522b9434ff.png)
> 
> This screen looks out of balance to me now 🤔

I agree. It's a draft, I'm trying to sync with a designer for this

2022-10-13 10:42 UTC, juliangruber requested changes
Aside from the loading screen, Lgtm! :)

2022-10-13 13:07 UTC, jopedroliveira commented
> Aside from the loading screen, Lgtm! :)

João Ferreira gave a good idea:
Change the step 2 Title to “Join the Filecoin Economy” but keep the text. And remove the slogan from splash screen

2022-10-13 15:01 UTC, bajtos commented on renderer/src/pages/Dashboard.tsx
> +              <p className="w-fit text-body-3xs text-grayscale-700 uppercase">Total Earnings (comming soon)</p>
I think the correct spelling is `coming`?

```suggestion
              <p className="w-fit text-body-3xs text-grayscale-700 uppercase">Total Earnings (coming soon)</p>
```

2022-10-14 10:11 UTC, juliangruber approved these changes

2022-10-17 08:36 UTC, merged